version: '3'
services: 
  flask:
    container_name: fg
    build: .
    image: zeltf
    volumes: 
      - ./tfgui:/home
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=tfgui.py
      - FLASK_DEBUG=1 # debug mode
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8

    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]
    #entrypoint: ["bash"]
    stdin_open: true #-i
    tty: true #-t